version: '3'
services:
  client:
    build:
      context: ./client 
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    image: gonr/pt:pt-client
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - VITE_URL=http://localhost:8080
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: gonr/pt:pt-server
    environment:
      - PORT=8080
      - DB_URL=postgresql://db_1_57z4_user:rCBCpSg2GCIIX77xV1eIw5IOMfYQNN4L@dpg-cukf1btds78s739n73pg-a.oregon-postgres.render.com/db_1_57z4